server:
  port: 8000
  error:
    include-stacktrace: always

spring:
  application:
    name: ecom
  profiles:
    active: default
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    cassandra:
      schema-action: create-if-not-exists
      keyspace-name: ${CASSANDRA_DB_KEYSPACE}
      contact-points: ${CASSANDRA_DB_ENDPOINTS}
      local-datacenter: ${CASSANDRA_DB_DC}
      port: 9042
      username: ${CASSANDRA_DB_USERNAME}
      password: ${CASSANDRA_DB_PASSWORD}
